import { db } from "./db";
import { useCases } from "./schema";

const SEED_DATA = [
  // Ready Now (score 70-100)
  {
    title: "AI-Powered Donor Thank You Letters",
    description: "Use generative AI tools like ChatGPT or Claude to draft personalized thank-you letters for donors. The AI can reference specific gift amounts, past giving history, and program impact to create warm, authentic correspondence at scale.",
    source_url: "https://www.nten.org",
    source_name: "NTEN",
    category: "Fundraising & Donor Relations",
    tier: "ready_now",
    score: 92,
    implementation_notes: "Start with ChatGPT or Claude. Create a template prompt that includes donor name, gift amount, and program area. Review and personalize each letter before sending. Most teams can be up and running in under an hour.",
    example_orgs: JSON.stringify(["United Way chapters", "Habitat for Humanity affiliates", "Local food banks"]),
    date_found: "2026-03-10",
  },
  {
    title: "Grant Proposal First Draft Generation",
    description: "AI assistants can generate first drafts of grant proposals by analyzing RFP requirements and your organization's past successful applications. This dramatically reduces the time from RFP to submission.",
    source_url: "https://www.techsoup.org",
    source_name: "TechSoup",
    category: "Fundraising & Donor Relations",
    tier: "ready_now",
    score: 85,
    implementation_notes: "Upload past successful proposals and the new RFP to Claude or ChatGPT. Ask it to draft sections following the RFP structure. Always have a human review and add organization-specific details.",
    example_orgs: JSON.stringify(["Community foundations", "Environmental nonprofits", "Youth development organizations"]),
    date_found: "2026-03-08",
  },
  {
    title: "Automated Social Media Content Creation",
    description: "Generate social media posts, captions, and hashtag strategies using AI. Tools can repurpose blog posts into platform-specific content and suggest optimal posting times.",
    source_url: "https://www.nonprofitmarketingguide.com",
    source_name: "Nonprofit Marketing Guide",
    category: "Marketing & Communications",
    tier: "ready_now",
    score: 88,
    implementation_notes: "Use tools like Canva's AI features or ChatGPT to generate content calendars. Feed in your mission statement and recent impact stories. Schedule posts using Buffer or Hootsuite.",
    example_orgs: JSON.stringify(["Charity: Water", "World Wildlife Fund", "Local humane societies"]),
    date_found: "2026-03-12",
  },
  {
    title: "AI Meeting Notes and Action Items",
    description: "Use AI transcription tools like Otter.ai or Fireflies to automatically capture meeting notes, extract action items, and distribute summaries to team members.",
    source_url: "https://www.techsoup.org",
    source_name: "TechSoup",
    category: "Operations & Admin",
    tier: "ready_now",
    score: 90,
    implementation_notes: "Sign up for Otter.ai or a similar service. Connect it to your video conferencing platform. After each meeting, review the auto-generated summary and share with your team.",
    example_orgs: JSON.stringify(["Red Cross chapters", "Boys & Girls Clubs", "Any nonprofit with regular meetings"]),
    date_found: "2026-03-05",
  },
  {
    title: "Chatbot for Beneficiary FAQs",
    description: "Deploy a simple AI chatbot on your website to answer frequently asked questions from beneficiaries about services, eligibility, hours, and locations. Reduces phone call volume and provides 24/7 support.",
    source_url: "https://www.idealware.org",
    source_name: "Idealware",
    category: "Program Delivery & Services",
    tier: "ready_now",
    score: 75,
    implementation_notes: "Use a no-code chatbot builder like Tidio or Drift. Train it on your FAQ page content. Start with the 20 most common questions and expand from there. Monitor conversations weekly.",
    example_orgs: JSON.stringify(["211 call centers", "Legal aid organizations", "Community health centers"]),
    date_found: "2026-03-11",
  },
  // Strategic Growth (score 40-69)
  {
    title: "Predictive Donor Churn Analysis",
    description: "Machine learning models that analyze giving patterns, engagement metrics, and demographic data to predict which donors are at risk of lapsing. Enables proactive retention outreach.",
    source_url: "https://ssir.org",
    source_name: "Stanford Social Innovation Review",
    category: "Fundraising & Donor Relations",
    tier: "strategic_growth",
    score: 55,
    implementation_notes: "Requires clean CRM data with 2+ years of giving history. Start with your CRM's built-in analytics or use a tool like DonorSearch. Consider hiring a data consultant for initial model setup.",
    example_orgs: JSON.stringify(["Large university foundations", "National health charities", "PBS stations"]),
    date_found: "2026-03-09",
  },
  {
    title: "Automated Volunteer-Opportunity Matching",
    description: "AI-powered systems that match volunteers with opportunities based on skills, availability, location, and interests. Improves volunteer satisfaction and reduces coordinator workload.",
    source_url: "https://www.pointsoflight.org",
    source_name: "Points of Light",
    category: "Volunteer Management",
    tier: "strategic_growth",
    score: 52,
    implementation_notes: "Implement a volunteer management platform with AI matching like Galaxy Digital or VolunteerHub. Requires structured volunteer profiles and opportunity descriptions. Budget for platform subscription and setup.",
    example_orgs: JSON.stringify(["HandsOn Network affiliates", "AmeriCorps programs", "Large hospital volunteer programs"]),
    date_found: "2026-03-07",
  },
  {
    title: "Sentiment Analysis for Program Feedback",
    description: "Use natural language processing to analyze open-ended survey responses, social media mentions, and feedback forms. Automatically categorize sentiment and identify recurring themes.",
    source_url: "https://www.nten.org",
    source_name: "NTEN",
    category: "Data & Impact Measurement",
    tier: "strategic_growth",
    score: 58,
    implementation_notes: "Export survey responses to a spreadsheet. Use Claude API or a tool like MonkeyLearn to classify sentiment. Create a dashboard to track sentiment trends over time. Requires some data cleanup.",
    example_orgs: JSON.stringify(["After-school programs", "Mental health organizations", "Community development CDFIs"]),
    date_found: "2026-03-06",
  },
  {
    title: "AI-Assisted Program Impact Reporting",
    description: "Generate narrative impact reports from quantitative data. AI tools can transform spreadsheet data into compelling stories for funders, boards, and stakeholders.",
    source_url: "https://ssir.org",
    source_name: "Stanford Social Innovation Review",
    category: "Data & Impact Measurement",
    tier: "strategic_growth",
    score: 62,
    implementation_notes: "Prepare a structured dataset of program outcomes. Use Claude or GPT-4 with a prompt template that includes your metrics and desired report format. Have program staff review for accuracy.",
    example_orgs: JSON.stringify(["Community action agencies", "Global health NGOs", "Education nonprofits"]),
    date_found: "2026-03-04",
  },
  {
    title: "Intelligent Document Processing for Intake",
    description: "AI-powered OCR and data extraction to process intake forms, applications, and supporting documents. Reduces manual data entry and speeds up beneficiary enrollment.",
    source_url: "https://www.techsoup.org",
    source_name: "TechSoup",
    category: "Operations & Admin",
    tier: "strategic_growth",
    score: 48,
    implementation_notes: "Evaluate tools like DocuSign Intelligent Insights or Google Document AI. Start with your highest-volume form type. Requires API integration with your case management system.",
    example_orgs: JSON.stringify(["Legal aid societies", "Refugee resettlement agencies", "Housing authorities"]),
    date_found: "2026-03-03",
  },
  {
    title: "AI-Powered Email Campaign Optimization",
    description: "Use AI to optimize email subject lines, send times, and content segmentation. Machine learning models learn from past campaign performance to improve open rates and engagement.",
    source_url: "https://www.nonprofitmarketingguide.com",
    source_name: "Nonprofit Marketing Guide",
    category: "Marketing & Communications",
    tier: "strategic_growth",
    score: 60,
    implementation_notes: "Most major email platforms (Mailchimp, Constant Contact) now offer AI features. Enable send-time optimization and subject line suggestions. Requires 6+ months of email campaign data for best results.",
    example_orgs: JSON.stringify(["National advocacy organizations", "Museum membership programs", "Alumni associations"]),
    date_found: "2026-03-02",
  },
  {
    title: "AI Legislative and Policy Monitoring",
    description: "AI tools that monitor legislative databases, news feeds, and government communications for policy changes relevant to your mission. Automatically alerts staff to relevant developments.",
    source_url: "https://www.councilofnonprofits.org",
    source_name: "National Council of Nonprofits",
    category: "Advocacy & Policy",
    tier: "strategic_growth",
    score: 45,
    implementation_notes: "Explore tools like Quorum, FiscalNote, or set up custom alerts with Claude API. Define your policy keywords and jurisdictions. Requires someone to review and act on alerts.",
    example_orgs: JSON.stringify(["ACLU chapters", "Environmental Defense Fund", "State nonprofit associations"]),
    date_found: "2026-03-01",
  },
  // Advanced Impact (score 1-39)
  {
    title: "Real-Time Crisis Intervention AI",
    description: "AI systems that monitor crisis hotline calls and texts in real-time, providing counselors with suggested resources, risk assessments, and escalation recommendations during live interactions.",
    source_url: "https://www.samhsa.gov",
    source_name: "SAMHSA",
    category: "Program Delivery & Services",
    tier: "advanced_impact",
    score: 18,
    implementation_notes: "This requires significant investment in custom AI development, clinical validation, and ethical review. Partner with an AI research institution. Budget 12-18 months for development and testing.",
    example_orgs: JSON.stringify(["Crisis Text Line", "988 Suicide & Crisis Lifeline", "Veterans Crisis Line"]),
    date_found: "2026-02-28",
  },
  {
    title: "Predictive Community Needs Assessment",
    description: "Large-scale AI models that combine census data, social determinants of health, economic indicators, and local data to predict emerging community needs before they become crises.",
    source_url: "https://ssir.org",
    source_name: "Stanford Social Innovation Review",
    category: "Data & Impact Measurement",
    tier: "advanced_impact",
    score: 22,
    implementation_notes: "Requires data science expertise, access to multiple datasets, and significant compute resources. Consider partnering with a university data science program. Start with a single geographic area.",
    example_orgs: JSON.stringify(["United Way of Greater Los Angeles", "Robin Hood Foundation", "Data.org"]),
    date_found: "2026-02-25",
  },
  {
    title: "AI-Driven Personalized Learning Pathways",
    description: "Custom AI models that create individualized education or training pathways for program participants based on their skills, goals, learning style, and progress.",
    source_url: "https://www.newamerica.org",
    source_name: "New America",
    category: "Program Delivery & Services",
    tier: "advanced_impact",
    score: 30,
    implementation_notes: "Requires integration with your LMS, custom model training on learner data, and ongoing algorithm refinement. Explore partnerships with EdTech companies or apply for technology grants.",
    example_orgs: JSON.stringify(["Khan Academy", "Year Up", "Goodwill Industries digital skills programs"]),
    date_found: "2026-02-20",
  },
];

export function seedDatabase() {
  const existing = db.select({ id: useCases.id }).from(useCases).all();
  if (existing.length > 0) {
    console.log(`Database already has ${existing.length} use cases, skipping seed.`);
    return;
  }

  for (const data of SEED_DATA) {
    db.insert(useCases).values(data).run();
  }
  console.log(`Seeded ${SEED_DATA.length} use cases.`);
}
